# Generated by Django 5.2.12 on 2026-04-27 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_remove_hotel_price_per_night_roomtype'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoomType',
        ),
    ]
