# Generated by Django 5.2.12 on 2026-04-27 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_delete_roomtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='hotel',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='hotels', to='hotels.amenity'),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('r_id', models.CharField(max_length=50)),
                ('r_type', models.CharField(max_length=100)),
                ('r_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('feature', models.TextField(blank=True, help_text='Specific room features or description')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='hotels.hotel')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('hotel', 'r_id'), name='unique_hotel_room_id')],
            },
        ),
    ]
