# Generated by Django 5.2.12 on 2026-05-03 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_name', models.CharField(help_text='Service Name (e.g., City General Hospital)', max_length=200)),
                ('es_contact', models.CharField(help_text='Contact Numbers', max_length=100)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_services', to='cities.city')),
            ],
        ),
    ]
