# Generated by Django 5.2.12 on 2026-04-29 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transportation',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False)),
                ('t_type', models.CharField(max_length=50)),
                ('t_desc', models.TextField()),
                ('apprx_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transportations', to='cities.city')),
            ],
        ),
    ]
