# Generated by Django 5.2.12 on 2026-04-25 12:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visited_at', models.DateTimeField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visited_by', to='cities.city')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='travel_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Travel History',
                'verbose_name_plural': 'Travel Histories',
                'ordering': ['-visited_at'],
                'unique_together': {('user', 'city')},
            },
        ),
    ]
