# Generated by Django 5.2.12 on 2026-04-27 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ag_id', models.CharField(max_length=50, unique=True)),
                ('ag_name', models.CharField(max_length=150)),
                ('ag_rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agencies', to='cities.city')),
            ],
        ),
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_id', models.CharField(max_length=50, unique=True)),
                ('g_name', models.CharField(max_length=150)),
                ('g_rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guides', to='agencies.agency')),
            ],
        ),
        migrations.CreateModel(
            name='GuideHire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hire_date', models.DateField()),
                ('days', models.PositiveIntegerField(default=1)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agencies.guide')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
