# Generated by Django 5.2.12 on 2026-04-27 18:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='guidehire',
            constraint=models.UniqueConstraint(fields=('guide', 'hire_date'), name='unique_guide_booking_per_day'),
        ),
    ]
