# Generated by Django 5.2.12 on 2026-05-03 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencies', '0002_guidehire_unique_guide_booking_per_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guidehire',
            name='status',
            field=models.CharField(default='Confirmed', max_length=20),
        ),
    ]
